# Generated by Django 4.0 on 2023-10-16 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            """
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

        CREATE TYPE user_feature_access_type AS ENUM (
            'sitter',
            'owner'
        );

        CREATE TYPE job_status AS ENUM (
            'open',
            'job_acceptance_pending',
            'acceptance_complete',
            'job_ongoing',
            'job_complete',
            'cancelled',
            'removed'
        );

        CREATE TYPE application_status AS ENUM (
            'rejected',
            'accepted'
        );
    """
        )
    ]
