# Generated by Django 4.0 on 2023-10-16 21:49

from django.db import migrations

migration_script = open("./sql/0001_create_first_db_models.sql").read().strip()


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunSQL(migration_script)]
