# Generated by Django 4.0 on 2023-10-20 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_column_type_custom_enums"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applications",
            old_name="job_id",
            new_name="job",
        ),
        migrations.RenameField(
            model_name="applications",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="jobs",
            old_name="location_id",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="jobs",
            old_name="pet_id",
            new_name="pet",
        ),
        migrations.RenameField(
            model_name="jobs",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="locations",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="pets",
            old_name="owner_id",
            new_name="owner",
        ),
    ]
