# Generated by Django 4.0 on 2023-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_users_options_alter_users_managers_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="applications",
            constraint=models.UniqueConstraint(
                fields=("user_id", "job_id"), name="user_id_job_id_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobs",
            constraint=models.UniqueConstraint(
                fields=("location_id", "start", "end", "pet_id"),
                name="location_id_start_end_pet_id_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="locations",
            constraint=models.UniqueConstraint(
                fields=("address", "city", "country"),
                name="address_city_country_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="pets",
            constraint=models.UniqueConstraint(
                fields=("name", "owner_id"), name="name_owner_id_constraint"
            ),
        ),
    ]
