# Generated by Django 4.0 on 2023-10-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_applications_user_id_job_id_constraint_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="locations",
            name="address_city_country_constraint",
        ),
        migrations.AddConstraint(
            model_name="locations",
            constraint=models.UniqueConstraint(
                fields=("address", "city", "country", "user_id"),
                name="address_city_country_user_id_constraint",
            ),
        ),
    ]
