# Generated by Django 4.0 on 2023-10-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_users_user_type'),
        ('api', '0008_remove_locations_address_city_country_constraint_and_more'),
    ]

    operations = [
    ]
