# Generated by Django 4.0 on 2023-11-27 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_locations_zipcode"),
        ("api", "0013_locations_zipcode_users_phone_number"),
    ]

    operations = []
