name: Django Backend Unit Tests
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8, 3.9 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd furbaby
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd furbaby
        export AWS_RDS_DATABASE_PASSWORD="dummy-password"
        export DJANGO_SECRET_KEY="dummy-secret-key"
        python manage.py test
